name: flutter_tex_example
description: A Flutter Package (Demo) to render LaTeX with full HTML and JavaScript support.
homepage: https://github.com/shahxadakram/flutter_tex

version: 3.6.7

publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex:
    path: ../
  webview_flutter_web: ^0.2.2+3
  dio: ^5.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  open_file: ^3.3.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/jsons/
    - assets/fonts/
    - assets/flutter_tex_banner.png
    - fonts/Army.ttf
    - fonts/Budhrg.ttf
    - fonts/CELTG.ttf
    - fonts/hillock.ttf
    - fonts/intimacy.ttf
    - fonts/SansationLight.ttf
    - fonts/slenmini.ttf
    - fonts/SubaccuzRegular.ttf
